// Beers
const data = [
  {
    id: 0,
    type: 'Amber Ale',
    brand: 'Beekers',
    desc: 'Bright & Bold',
    url: './images/beers/amber-ale.jpg',
    active: false,
  },
  {
    id: 1,
    type: 'Cider',
    brand: 'Moon Crew',
    desc: 'Silky & Smooth',
    url: './images/beers/cider.jpg',
    active: false,
  },
  {
    id: 2,
    type: 'IPA',
    brand: 'Determinator',
    desc: 'Floral & Piney',
    url: './images/beers/ipa.jpg',
    active: false,
  },
  {
    id: 3,
    type: 'IPA',
    brand: 'Little Bunny',
    desc: 'Fruity & Strong',
    url: './images/beers/ipa2.jpg',
    active: false,
  },
  {
    id: 4,
    type: 'Lager',
    brand: 'Tuengling',
    desc: 'Light & Crisp',
    url: './images/beers/lager.jpg',
    active: false,
  },
  {
    id: 5,
    type: 'Lager',
    brand: 'Liquid Karma',
    desc: 'Mellow & Smooth',
    url: './images/beers/lager2.jpg',
    active: false,
  },
  {
    id: 6,
    type: 'Pilsner',
    brand: 'Cosmic Hops',
    desc: 'Light & Floral',
    url: './images/beers/pilsner.jpg',
    active: false,
  },
  {
    id: 7,
    type: 'Pilsner',
    brand: 'Lards',
    desc: 'Crisp & Golden',
    url: './images/beers/pilsner2.jpg',
    active: false,
  },
  {
    id: 8,
    type: 'Wheat',
    brand: 'Nice To Wheat You',
    desc: 'Mild & Refreshing',
    url: './images/beers/wheat.jpg',
    active: false,
  },
];
